# Generated by Django 5.0 on 2024-11-11 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_categoria", models.CharField(max_length=100)),
                ("descripcion_categoria", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Dibujos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_dibujo", models.CharField(max_length=100)),
                ("imagen", models.ImageField(upload_to="img/")),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="draw_app.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MisSolicitudesUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("en_espera", "En Espera"),
                            ("en_proceso", "En Proceso"),
                            ("finalizado", "Finalizado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="en_espera",
                        max_length=20,
                    ),
                ),
                ("referencia", models.ImageField(upload_to="", verbose_name="img/")),
                ("descripcion", models.CharField(max_length=500)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="draw_app.categoria",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolicitudAdministrador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precio_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "solicitudes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="draw_app.missolicitudesusuario",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
