# Generated by Django 5.0 on 2024-11-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draw_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="missolicitudesusuario",
            name="precio_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="missolicitudesusuario",
            name="estado",
            field=models.CharField(
                choices=[
                    ("en_espera", "En Espera"),
                    ("en_proceso", "En Proceso"),
                    ("finalizado", "Finalizado"),
                    ("rechazado", "Rechazado"),
                ],
                default="En Espera",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="SolicitudAdministrador",
        ),
    ]
